### ISSUE TITLE
Shows logged in information/button when logged in

### ISSUE THREAD

**Issue by MiguelLeyesa** [Skentir/LayerTech-v2.0#35]
Date: Jan 15, 2021
By: Team Blended-not-Stirred
Branch: main
Browser: Firefox

Type: 
(**Coding Error** / Design Issue / Suggestion)

Severity: (Fatal / Serious / **Minor**)

Sceenshot
![image](https://user-images.githubusercontent.com/61416986/104694721-8e338380-5746-11eb-965b-c3f364cd780d.png)

Description: 
Log out button and FirstName LastName container is already shown to the user even if the user hasn't logged in yet. 

Steps to Replicate: 
1. Go to http://localhost:8080/#/

Suggested Fix (Optional): 
Remove “FirstName Lastname” when not logged in
Change the logout button to login when the information should be for “logged out” users

**Comment by rainecortel** [comment]
DATE: January 18, 2021

BY: Howard & Friends

BRANCH: Main

BROWSER: Google Chrome Version 87.0.4280.141 (64-bit)

TYPE:
(**Coding Error** / Design Issue / Suggestion)

SEVERITY:
(Fatal / Serious / **Minor**)

DESCRIPTION:
Upon arriving on the landing page, there is already a logout button on the top-right of the screen, and login credentials 'FirstName LastName' is already displayed even if the user is not yet logged in.

STEPS TO REPLICATE:
1. Run the application on localhost:8080.

EXPECTED RESULTS:
There should be no logout button on the landing page and login credentials such as first name and last name should not be shown to a logged-out user.

ACTUAL RESULTS:
Log out button is visible along with the login credentials.

SCREENSHOTS:
![image](https://user-images.githubusercontent.com/61410465/104915393-89cbcc80-59cb-11eb-901f-0e2fc5da033e.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
