### ISSUE TITLE
Log in link should be where the logout button is

### ISSUE THREAD

**Issue by MiguelLeyesa** [Skentir/LayerTech-v2.0#37]
Date: Jan 15, 2021
By: Team Blended-not-Stirred
Branch: main
Browser: Firefox

Type: 
(Coding Error / Design Issue / **Suggestion**)

Severity: 
(Fatal / Serious / **Minor**)

Screenshot:
![image](https://user-images.githubusercontent.com/61416986/104695224-5b3dbf80-5747-11eb-8523-e1e07e880e59.png)

Description:
The web-app shows information already made for “logged in” users, even though the user is not yet logged in.
The default information shown should be for non logged in users.

Steps to Replicate:
1. Go to http://localhost:8080/#/

Suggested Fix (Optional):
![image](https://user-images.githubusercontent.com/61416986/104695265-6c86cc00-5747-11eb-86cd-1ce28e4fe7f3.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
