### ISSUE TITLE
Elements at the Log-in page

### ISSUE THREAD

**Issue by drbuhion** [Skentir/LayerTech-v2.0#38]
Date: Jan 15, 2021

By: samGROUPsal

Branch: main

Browser: Chrome

Type:
(Coding Error / **Design Issue** / Suggestion)

Severity:
(Fatal / **Serious** / Minor)

Screenshot:
![f](https://user-images.githubusercontent.com/7200360/104731666-031eb180-5777-11eb-91c5-7d5a737dbdff.JPG)

Description:
The size of the box for log-in is not correct and there is a bar that covers some part of the screen.

Steps to Replicate:
1. Go to http://localhost:8080/#/

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
