### ISSUE TITLE
Empty fields at Add Employee

### ISSUE THREAD

**Issue by drbuhion** [Skentir/LayerTech-v2.0#39]
Date: Jan 15, 2021

By: samGROUPsal

Branch: main

Browser: Chrome

Type:
(Coding Error / Design Issue / **Suggestion**)

Severity:
(Fatal / **Serious** / Minor)

Screenshot: (First row shows an employee with empty details)
![g](https://user-images.githubusercontent.com/7200360/104731991-79bbaf00-5777-11eb-8f03-f23f45a1df47.JPG)

Description:
Add employee proceeds even if there were no data entered on the fields. There is also no error checking among the fields.

Steps to Replicate:
1. Go to http://localhost:8080/#/
2. Log-in
3. Select Employees
4. Add Employee
5. Enter data on the fields
6. Click Save

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
