### ISSUE TITLE
Suggested value at the Unit placeholder

### ISSUE THREAD

**Issue by drbuhion** [Skentir/LayerTech-v2.0#40]
Date: Jan 15, 2021

By: samGROUPsal

Branch: main

Browser: Chrome

Type:
(Coding Error / **Design Issue** / Suggestion)

Severity:
(Fatal / Serious / **Minor**)

Screenshot:
![e](https://user-images.githubusercontent.com/7200360/104732259-e6cf4480-5777-11eb-9ec7-32ad085a2726.JPG)

Description:
The suggested value in the Unit placeholder is a number when the expected value to be placed by the user should be a string.

Steps to Replicate:
1. Go to http://localhost:8080/#/
2. Log-in
3. Select Operations
4. Select Add Item

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
