### ISSUE TITLE
 negative zero in contact number of employee

### ISSUE THREAD

**Issue by Plumman** [Skentir/LayerTech-v2.0#41]
By: Jamie & Curry Co.

Branch: main

Browser: Chrome

Type:
(Coding Error / **Design Issue** / Suggestion)

Severity:
(Minor)

Description:
It is possible to input negative number in contact number of employee

Steps to Replicate:

Go to http://localhost:8080/#/
Log-in
Select Employees
Click on the edit icon on the right of the person
Enter negative 10 as the contact number
Click Save

Screenshots:
Putting negative 10
![image](https://user-images.githubusercontent.com/51822908/104839892-25433b80-58ff-11eb-8f91-8527b04980e7.png)

After clicking save
![image](https://user-images.githubusercontent.com/51822908/104839901-30966700-58ff-11eb-9ae6-2362094e1584.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
