### ISSUE TITLE
letters in contact number of employee

### ISSUE THREAD

**Issue by Plumman** [Skentir/LayerTech-v2.0#42]
By: Jamie & Curry Co.

Branch: main

Browser: Chrome

Type:
(Design Issue)

Severity:
(Minor)

Description:
It is possible to input letters in contact number of employee

Steps to Replicate:

Go to http://localhost:8080/#/
Log-in
Select Employees
Click on the edit icon on the right of the person
Enter letters in the contact number
Click Save

Screenshots:
Putting letters
![image](https://user-images.githubusercontent.com/51822908/104839836-c67dc200-58fe-11eb-8bbb-a3cb528c96a6.png)

Saving the contact number
![image](https://user-images.githubusercontent.com/51822908/104839841-d2698400-58fe-11eb-9f61-2424a0720620.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
