### ISSUE TITLE
input blanks in the information of employees

### ISSUE THREAD

**Issue by Plumman** [Skentir/LayerTech-v2.0#45]
By: Jamie & Curry Co.

Branch: main

Browser: Chrome

Type:
(Design Issue)

Severity:
(Minor)

Description:
It is possible to input blanks in the information of employees

Steps to Replicate:

Go to http://localhost:8080/#/
Log-in
Select Employees
Click on the edit icon on the right of the person
Enter blanks on the information
Click Save

Screenshots:
erasing information
![image](https://user-images.githubusercontent.com/51822908/104839959-7bb07a00-58ff-11eb-9eba-a8ab1198839e.png)

after clicking save
![image](https://user-images.githubusercontent.com/51822908/104840020-cf22c800-58ff-11eb-837d-2d823fed032a.png)

**Comment by rainecortel** [comment]
DATE: January 18, 2021

BY: Howard & Friends

BRANCH: Main

BROWSER: Google Chrome Version 87.0.4280.141 (64-bit)

TYPE:
(**Coding Error** / Design Issue / Suggestion)

SEVERITY:
(Fatal / **Serious** / Minor)

DESCRIPTION:
When adding a new employee, even if the fields are blank, a new employee row will be added if 'Save' is clicked.

STEPS TO REPLICATE:
1. Run the application on localhost:8080.
2. Login using the provided credentials.
3. Select 'Employees'.
4. Click 'Add Employee'
5. Click 'Save' even if the fields (or some of the fields) are empty.

EXPECTED RESULTS:
Blank data should not be accepted by the web application. The web application should also not accept incomplete data from the user's input.

ACTUAL RESULTS:
Blank data and incomplete data are still accepted and they create a new row.

SCREENSHOTS:
![image](https://user-images.githubusercontent.com/61410465/104901843-dd80ea80-59b8-11eb-8550-a650bd0eefb7.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
