### ISSUE TITLE
input letters in the quantity of operations

### ISSUE THREAD

**Issue by Plumman** [Skentir/LayerTech-v2.0#46]
By: Jamie & Curry Co.

Branch: main

Browser: Chrome

Type:
(Design Issue)

Severity:
(Minor)

Description:
It is possible to input letters in the quantity of operations

Steps to Replicate:

Go to http://localhost:8080/#/
Log-in
Select Operations
Click on the edit icon on the right of the row
Enter letters on the quantity
Click Save

Screenshots:
enter letters
![image](https://user-images.githubusercontent.com/51822908/104840090-3a6c9a00-5900-11eb-8a86-75aca60a83ee.png)

click on save
![image](https://user-images.githubusercontent.com/51822908/104840106-4f492d80-5900-11eb-9314-041a3b3ccff7.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
