### ISSUE TITLE
[Navigation] Home button redirects to login page

### ISSUE THREAD

**Issue by clvsantos** [Skentir/LayerTech-v2.0#47]
Summary:
Clicking Home button redirects to login page

Steps to Reproduce:

Run app in localhost:8080
Login with credentials "admin123" and "correctPassword"
Go to Operations
Click home button in navbar
Goes to login page
Actual Result:
![image](https://user-images.githubusercontent.com/58662255/104840069-1b6e0800-5900-11eb-8022-1e8bd53aaeac.png)

Expected Result:

Redirected to /home.

Tested on:

Branch: main
Browser: Microsoft Edge (Chromium)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
