### ISSUE TITLE
Cannot Logout

### ISSUE THREAD

**Issue by Plumman** [Skentir/LayerTech-v2.0#48]
By: Jamie & Curry Co.

Branch: main

Browser: Chrome

Type:
(**Coding Error** / Design Issue / Suggestion)

Severity:
(Fatal / **Serious** / Minor)

Description:
It is not possible to logout after logging in

Steps to Replicate:

Go to http://localhost:8080/#/
Log-in
Click Logout button

Screenshots:
Clicking logout does not do anything
![image](https://user-images.githubusercontent.com/51822908/104843089-d4821180-5903-11eb-8937-81438b6a174f.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
