### ISSUE TITLE
Clicking reset does not do anything

### ISSUE THREAD

**Issue by Plumman** [Skentir/LayerTech-v2.0#49]
By: Jamie & Curry Co.

Branch: main

Browser: Chrome

Type:
(Coding Error / **Design Issue** / Suggestion)

Severity:
(Fatal / Serious / **Minor**)

Description:
Clicking reset does not do anything

Steps to Replicate:

Go to http://localhost:8080/#/
Log-in
Select Employees
Delete all rows
Click on Reset

Screenshots:
After deleting all rows
![image](https://user-images.githubusercontent.com/51822908/104843236-7570cc80-5904-11eb-95b4-50082223f2e9.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
