### ISSUE TITLE
Refreshing removes newly added data.

### ISSUE THREAD

**Issue by rainecortel** [Skentir/LayerTech-v2.0#51]
DATE: January 18, 2021

BY: Howard & Friends

BRANCH: Main

BROWSER: Google Chrome Version 87.0.4280.141 (64-bit)

TYPE:
(**Coding Error** / Design Issue / Suggestion)

SEVERITY:
(**Fatal** / Serious / Minor)

DESCRIPTION:
Refreshing the website through the refresh button or F5 removes newly added data in the Employees and Operations section. However, when trying to log back in again (without refreshing), the data is still present.

STEPS TO REPLICATE:
1. Run the application on localhost:8080.
2. Login using the provided credentials.
3. Select 'Employees'.
4. Click 'Add Employee' and add new data, then save the new entry.
5. Select 'Operations'.
6. Click 'Add Item' and add new data, then save the new entry.
7. Refresh the whole site.

EXPECTED RESULTS:
The newly added data should remain in the web application even after refreshing the web application.

ACTUAL RESULTS:
Data was removed after refreshing.

SCREENSHOTS:
• New entry in Employees.
![image](https://user-images.githubusercontent.com/61410465/104902846-356c2100-59ba-11eb-9980-7fc03e030adb.png)

• New entry in Operations.
![image](https://user-images.githubusercontent.com/61410465/104902907-49b01e00-59ba-11eb-8ec9-c9d1ae6b2a57.png)

• Logging back in and data is still present.
![image](https://user-images.githubusercontent.com/61410465/104902970-5f254800-59ba-11eb-83cc-d532fb9f94a1.png)
![image](https://user-images.githubusercontent.com/61410465/104903005-6b110a00-59ba-11eb-9bda-318e2a84113c.png)
![image](https://user-images.githubusercontent.com/61410465/104903029-76643580-59ba-11eb-892a-3c09f4009d80.png)

• After refresh.
![image](https://user-images.githubusercontent.com/61410465/104903165-a01d5c80-59ba-11eb-9f3e-db51806211bf.png)
![image](https://user-images.githubusercontent.com/61410465/104903193-a6abd400-59ba-11eb-8261-3e099c246bce.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
