### ISSUE TITLE
Clicking 'Login' redirects to blank page.

### ISSUE THREAD

**Issue by rainecortel** [Skentir/LayerTech-v2.0#52]
DATE: January 18, 2021

BY: Howard & Friends

BRANCH: Main

BROWSER: Google Chrome Version 87.0.4280.141 (64-bit)

TYPE:
(**Coding Error** / Design Issue / Suggestion)

SEVERITY:
(Fatal / **Serious** / Minor)

DESCRIPTION:
Clicking the 'Login' navigation at the top of the page redirects to a blank page.

STEPS TO REPLICATE:
1. Run the application on localhost:8080.
2. Click 'Login'.

EXPECTED RESULTS:
The Login navigation should redirect the user back to the login page of the web application.

ACTUAL RESULTS:
The user was redirected to a blank page.

SCREENSHOTS:
• From landing page to 'Login' page.
![image](https://user-images.githubusercontent.com/61410465/104903687-4ff2ca00-59bb-11eb-8ab2-94af2b6d0c6c.png)
![image](https://user-images.githubusercontent.com/61410465/104903725-58e39b80-59bb-11eb-860b-9fc210703941.png)

• From home to 'Login' page.
![image](https://user-images.githubusercontent.com/61410465/104903787-6d279880-59bb-11eb-9c80-c825b0a15d9f.png)
![image](https://user-images.githubusercontent.com/61410465/104903817-73b61000-59bb-11eb-8437-201cece5e329.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
