### ISSUE TITLE
Non-logged in user can add information to the website.

### ISSUE THREAD

**Issue by rainecortel** [Skentir/LayerTech-v2.0#53]
DATE: January 18, 2021

BY: Howard & Friends

BRANCH: Main

BROWSER: Google Chrome Version 87.0.4280.141 (64-bit)

TYPE:
(**Coding Error** / Design Issue / Suggestion)

SEVERITY:
(Fatal / **Serious** / Minor)

DESCRIPTION:
Given the pre-requirement of having user credentials, non-logged-in users can add information to the website simply by going to the Employees and Operations webpage.

STEPS TO REPLICATE:
1. Run the application on localhost:8080.
2. Select Employees from the top navigation bar.
3. Add a new employee data and save it to add a new row.
4. Select Operations from the top navigation bar.
5. Add a new item data and save it to add a new row.

EXPECTED RESULTS:
Non-logged-in users should not be able to add data to the web application.

ACTUAL RESULTS:
Non-logged-in users are able to add data to the web application.

SCREENSHOTS:
![image](https://user-images.githubusercontent.com/61410465/104916713-67d34980-59cd-11eb-86cd-ae6915614928.png)
![image](https://user-images.githubusercontent.com/61410465/104918040-280d6180-59cf-11eb-8d53-4d398a0a3944.png)
![image](https://user-images.githubusercontent.com/61410465/104918169-555a0f80-59cf-11eb-8515-0363f8e5f7e2.png)

**Comment by AxelAlba** [comment]
This is resolved. You may test it on the latest dev branch (Follow the README.md to run) or the deployed website.
